# ============================================================
#  SkillBarter Automation – Staging Configuration
#  Switch to this file by setting -Denv=staging in Maven
# ============================================================

base.url=https://staging.skill-barter-wine-theta.vercel.app/
browser=chrome
headless=true
valid.email=staging-user@test.com
valid.password=Staging@123
implicit.wait=10
explicit.wait=20
page.load.timeout=45
reports.path=test-output/reports/ExtentReport-Staging.html
screenshots.path=test-output/screenshots/
testdata.path=src/test/resources/testdata/TestData.xlsx
